"""reviews random

Revision ID: 518a6023ce24
Revises: c03be4fbe95f
Create Date: 2024-11-21 22:53:17.411997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migration.TableInit import TableInit

# revision identifiers, used by Alembic.
revision: str = '518a6023ce24'
down_revision: Union[str, None] = 'c03be4fbe95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    review = sa.Table('user_review_movies', sa.MetaData(), autoload_with = op.get_bind())
    TableInit.insert_data_from_file(review, 'migration/versions/csv_data/user_reviews_clear.csv', [ 'movie_id', 'user_id', 'header', 'review', 'statement'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    review = sa.Table('user_review_movies', sa.MetaData(), autoload_with = op.get_bind())
    op.execute(review.delete())
    # ### end Alembic commands ###
