"""user role

Revision ID: b043524c6349
Revises: 518a6023ce24
Create Date: 2024-11-23 22:15:56.772378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b043524c6349'
down_revision: Union[str, None] = '518a6023ce24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = postgresql.ENUM('admin', 'moderator', 'user', name='userrole')
    userrole.create(op.get_bind())
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='userrole'), server_default='user', nullable=False))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    userrole = postgresql.ENUM('admin', 'moderator', 'user', name='userrole')
    userrole.drop(op.get_bind())
    # ### end Alembic commands ###
