"""rename column movies

Revision ID: dc268ed34399
Revises: 1b0ee105ee9d
Create Date: 2024-11-14 22:51:03.341370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc268ed34399'
down_revision: Union[str, None] = '1b0ee105ee9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name = 'movies', column_name = 'movies_rating_sum', new_column_name = 'movie_rating_sum')
    op.alter_column(table_name = 'movies', column_name = 'movies_rating_count', new_column_name = 'movie_rating_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name = 'movies', column_name = 'movie_rating_sum', new_column_name = 'movies_rating_sum')
    op.alter_column(table_name = 'movies', column_name = 'movie_rating_count', new_column_name = 'movies_rating_count')
    # ### end Alembic commands ###
