"""rebild train

Revision ID: f9713a5d7be4
Revises: 32f9e2f47d61
Create Date: 2024-12-22 04:05:24.999430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9713a5d7be4'
down_revision: Union[str, None] = '32f9e2f47d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommedation', 'recommedation',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True,
               existing_server_default=sa.text('ARRAY[858, 318, 7502, 50, 1221, 2019, 296, 922, 1198, 904]'))
    op.add_column('train_ratings', sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.alter_column('train_ratings', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('train_ratings', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_column('train_ratings', 'id')
    op.alter_column('recommedation', 'recommedation',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False,
               existing_server_default=sa.text('ARRAY[858, 318, 7502, 50, 1221, 2019, 296, 922, 1198, 904]'))
    # ### end Alembic commands ###
