"""Cascade

Revision ID: ebde7a072b5e
Revises: 8cee47714e34
Create Date: 2024-10-09 20:04:11.523751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebde7a072b5e'
down_revision: Union[str, None] = '8cee47714e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('links_movie_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key('links_movie_id_fkey', 'links', 'movies', ['movie_id'], ['movie_id'], ondelete='CASCADE')
    op.drop_constraint('users_watch_history_user_id_fkey', 'users_watch_history', type_='foreignkey')
    op.create_foreign_key('users_watch_history_user_id_fkey', 'users_watch_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_watch_history_user_id_fkey', 'users_watch_history', type_='foreignkey')
    op.create_foreign_key('users_watch_history_user_id_fkey', 'users_watch_history', 'users', ['user_id'], ['id'])
    op.drop_constraint('links_movie_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key('links_movie_id_fkey', 'links', 'movies', ['movie_id'], ['movie_id'])
    # ### end Alembic commands ###
